ifeq ($(CONFIG_ARCH_SUN), y)
	include $(AUDIO_ROOT)/config/sunauto.conf
	export INCS += -include $(AUDIO_ROOT)/config/sunautoconf.h
endif

obj-y := dsp/ ipc/ soc/ asoc/ asoc/codecs/ asoc/codecs/lpass-cdc/ asoc/codecs/bolero/ asoc/codecs/wcd939x/ asoc/codecs/wsa884x/ asoc/codecs/wcd938x/ asoc/codecs/wsa883x/ asoc/codecs/wcd937x/ asoc/codecs/wcd9378/ asoc/codecs/qmp1000/
